name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ./.github/actions/install-rust
      with:
        toolchain: stable
    - run: cargo fmt --all -- --check

  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, beta, nightly]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: nightly
            os: ubuntu-latest
            rust: nightly

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ./.github/actions/install-rust
      with:
        toolchain: ${{ matrix.rust }}
    - run: >
        rustup target add
        x86_64-unknown-linux-musl
        x86_64-unknown-linux-gnux32
        x86_64-linux-android
        x86_64-apple-darwin
        x86_64-unknown-freebsd
        x86_64-unknown-netbsd
        x86_64-fuchsia
        i686-unknown-linux-gnu
        i686-unknown-linux-musl
        wasm32-unknown-emscripten
        riscv64gc-unknown-linux-gnu
        aarch64-unknown-linux-gnu
    - run: cargo check --workspace --release -vv
    - run: cargo check --workspace --release -vv --target=x86_64-unknown-linux-musl
    - run: cargo check --workspace --release -vv --target=x86_64-unknown-linux-gnux32
    - run: cargo check --workspace --release -vv --target=x86_64-linux-android
    - run: cargo check --workspace --release -vv --target=x86_64-apple-darwin
    - run: cargo check --workspace --release -vv --target=x86_64-unknown-freebsd
    - run: cargo check --workspace --release -vv --target=x86_64-unknown-netbsd
    - run: cargo check --workspace --release -vv --target=x86_64-fuchsia
    - run: cargo check --workspace --release -vv --target=i686-unknown-linux-gnu
    - run: cargo check --workspace --release -vv --target=i686-unknown-linux-musl
    - run: cargo check --workspace --release -vv --target=wasm32-unknown-emscripten
    - run: cargo check --workspace --release -vv --target=riscv64gc-unknown-linux-gnu
    - run: cargo check --workspace --release -vv --target=aarch64-unknown-linux-gnu

  check_nightly:
    name: Check on Rust nightly
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [nightly]
        include:
          - build: nightly
            os: ubuntu-latest
            rust: nightly

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ./.github/actions/install-rust
      with:
        toolchain: ${{ matrix.rust }}
    - run: >
        rustup target add
        x86_64-unknown-redox
        wasm32-wasi
    - run: cargo check --workspace --release -vv --target=x86_64-unknown-redox
    - run: cargo check --workspace --release -vv --target=wasm32-wasi


  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ubuntu, macos]
        include:
          - build: ubuntu
            os: ubuntu-latest
            rust: stable
          - build: macos
            os: macos-latest
            rust: stable
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ./.github/actions/install-rust
      with:
        toolchain: ${{ matrix.rust }}
    - run: >
        cargo test
